/**
 * In-Memory & Production Data Store for Perzent
 * Provides ultra-fast local development and testing with realistic seed data
 */
import {
  AuthSession,
  AttendanceSummary,
  DailyRoutePlayback,
  LiveTeamMember,
  SYSTEM_CONFIG,
  PaymentTransaction,
  EMPLOYEE_BASE_PRICE_INR,
  GST_AMOUNT_INR,
  EMPLOYEE_TOTAL_PRICE_INR,
} from '@perzent/shared-types';

export interface DBStore {
  companies: any[];
  departments: any[];
  users: any[];
  userDevices: any[];
  attendanceRecords: any[];
  attendanceBreaks: any[];
  locationStops: any[];
  locationWaypoints: any[];
  tamperLogs: any[];
  paymentTransactions: PaymentTransaction[];
}

declare global {
  var __PERZENT_STORE__: DBStore | undefined;
}

export function getStore(): DBStore {
  if (!globalThis.__PERZENT_STORE__) {
    globalThis.__PERZENT_STORE__ = seedInitialStore();
  }
  return globalThis.__PERZENT_STORE__;
}

function seedInitialStore(): DBStore {
  const companyId = 'comp-acme-1001';
  const deptNorthId = 'dept-north-sales';
  const deptLogisticsId = 'dept-logistics-ops';

  const ownerId = 'user-rajesh-owner';
  const managerPriyaId = 'user-priya-manager';
  const employeeAmitId = 'user-amit-employee';
  const employeeSnehaId = 'user-sneha-employee';
  const employeeVikramId = 'user-vikram-employee';

  const todayStr = new Date().toISOString().split('T')[0];

  return {
    companies: [
      {
        id: companyId,
        name: 'Acme Logistics Pvt Ltd',
        owner_email: 'rajesh@acmelogistics.com',
        timezone: 'Asia/Kolkata',
        auto_checkout_time: '23:40',
        max_break_minutes: 30,
        route_retention_days: 15,
        attendance_retention_days: 45,
        plan_tier: 'FREE',
        created_at: new Date().toISOString(),
      },
    ],
    departments: [
      { id: deptNorthId, company_id: companyId, name: 'North Delhi Sales Hub' },
      { id: deptLogisticsId, company_id: companyId, name: 'Field Logistics Operations' },
    ],
    users: [
      {
        id: ownerId,
        company_id: companyId,
        full_name: 'Rajesh Sharma',
        email: 'rajesh@acmelogistics.com',
        phone: '+919876543210',
        password: 'password123',
        role: 'OWNER',
        designation: 'Managing Director & Owner',
        status: 'ACTIVE',
      },
      {
        id: managerPriyaId,
        company_id: companyId,
        department_id: deptNorthId,
        full_name: 'Priya Verma',
        email: 'priya.verma@acmelogistics.com',
        phone: '+919811122200',
        password: 'password123',
        role: 'MANAGER',
        designation: 'Regional Sales Manager',
        status: 'ACTIVE',
      },
      {
        id: employeeAmitId,
        company_id: companyId,
        department_id: deptNorthId,
        manager_id: managerPriyaId,
        full_name: 'Amit Kumar',
        email: 'amit.kumar@acmelogistics.com',
        phone: '+919811122233',
        password: 'password123',
        role: 'EMPLOYEE',
        designation: 'Senior Field Sales Executive',
        status: 'ACTIVE',
      },
      {
        id: employeeSnehaId,
        company_id: companyId,
        department_id: deptNorthId,
        manager_id: managerPriyaId,
        full_name: 'Sneha Patel',
        email: 'sneha.patel@acmelogistics.com',
        phone: '+919811122244',
        password: 'password123',
        role: 'EMPLOYEE',
        designation: 'Client Relationship Officer',
        status: 'ACTIVE',
      },
      {
        id: employeeVikramId,
        company_id: companyId,
        department_id: deptLogisticsId,
        full_name: 'Vikram Singh',
        email: 'vikram.singh@acmelogistics.com',
        phone: '+919811122255',
        password: 'password123',
        role: 'EMPLOYEE',
        designation: 'Logistics Fleet Supervisor',
        status: 'ACTIVE',
      },
    ],
    userDevices: [
      {
        id: 'dev-amit-samsung',
        user_id: employeeAmitId,
        device_uuid: 'DEV-SAMSUNG-A54-8899',
        device_model: 'Samsung Galaxy A54 5G',
        os_version: 'Android 14 (OneUI 6.1)',
        is_active: true,
        last_seen_at: new Date().toISOString(),
        telemetry: {
          battery_level: 88,
          battery_status: 'CHARGING',
          battery_health: 'GOOD',
          battery_temperature: 31.8,
          battery_power_save: false,
          sound_volume: 75,
          sound_mode: 'NORMAL',
          brightness_level: 80,
          brightness_auto: true,
          storage_used_gb: 58.4,
          storage_total_gb: 128.0,
          storage_free_gb: 69.6,
          storage_free_pct: 54.4,
          ram_used_gb: 4.6,
          ram_total_gb: 8.0,
          ram_usage_pct: 57.5,
          updated_at: new Date().toISOString(),
        },
      },
      {
        id: 'dev-sneha-oneplus',
        user_id: employeeSnehaId,
        device_uuid: 'DEV-ONEPLUS-11R-3322',
        device_model: 'OnePlus 11R',
        os_version: 'Android 14 (OxygenOS 14)',
        is_active: true,
        last_seen_at: new Date().toISOString(),
        telemetry: {
          battery_level: 64,
          battery_status: 'DISCHARGING',
          battery_health: 'GOOD',
          battery_temperature: 33.2,
          battery_power_save: false,
          sound_volume: 0,
          sound_mode: 'VIBRATE',
          brightness_level: 65,
          brightness_auto: true,
          storage_used_gb: 92.1,
          storage_total_gb: 256.0,
          storage_free_gb: 163.9,
          storage_free_pct: 64.0,
          ram_used_gb: 6.2,
          ram_total_gb: 16.0,
          ram_usage_pct: 38.8,
          updated_at: new Date().toISOString(),
        },
      },
      {
        id: 'dev-vikram-redmi',
        user_id: employeeVikramId,
        device_uuid: 'DEV-REDMI-NOTE13-7711',
        device_model: 'Redmi Note 13 Pro',
        os_version: 'Android 14 (HyperOS)',
        is_active: true,
        last_seen_at: new Date().toISOString(),
        telemetry: {
          battery_level: 92,
          battery_status: 'DISCHARGING',
          battery_health: 'GOOD',
          battery_temperature: 29.5,
          battery_power_save: false,
          sound_volume: 85,
          sound_mode: 'NORMAL',
          brightness_level: 90,
          brightness_auto: false,
          storage_used_gb: 38.0,
          storage_total_gb: 64.0,
          storage_free_gb: 26.0,
          storage_free_pct: 40.6,
          ram_used_gb: 3.5,
          ram_total_gb: 6.0,
          ram_usage_pct: 58.3,
          updated_at: new Date().toISOString(),
        },
      },
    ],
    attendanceRecords: [
      {
        id: 'att-amit-today',
        user_id: employeeAmitId,
        work_date: todayStr,
        punch_in_time: `${todayStr}T09:30:00.000Z`,
        punch_out_time: null,
        punch_in_by: 'EMPLOYEE',
        punch_out_by: null,
        punch_in_lat: 28.6289,
        punch_in_lng: 77.3752,
        status: 'CHECKED_IN',
        gross_worked_minutes: 240,
        total_break_minutes: 0,
        net_worked_minutes: 240,
      },
      {
        id: 'att-sneha-today',
        user_id: employeeSnehaId,
        work_date: todayStr,
        punch_in_time: `${todayStr}T09:00:00.000Z`,
        punch_out_time: null,
        punch_in_by: 'EMPLOYEE',
        punch_out_by: null,
        punch_in_lat: 28.5355,
        punch_in_lng: 77.3910,
        status: 'ON_BREAK',
        gross_worked_minutes: 270,
        total_break_minutes: 18,
        net_worked_minutes: 252,
      },
    ],
    attendanceBreaks: [
      {
        id: 'brk-sneha-today',
        attendance_id: 'att-sneha-today',
        break_type: 'LUNCH',
        start_time: new Date(Date.now() - 12 * 60000).toISOString(),
        end_time: null,
        duration_minutes: 12,
        ended_by: null,
      },
    ],
    locationStops: [
      {
        id: 'stop-amit-1',
        attendance_id: 'att-amit-today',
        user_id: employeeAmitId,
        latitude: 28.6289,
        longitude: 77.3752,
        address_name: 'Head Office, Sector 62, Noida',
        start_time: `${todayStr}T09:30:00.000Z`,
        end_time: `${todayStr}T11:00:00.000Z`,
        dwell_duration_seconds: 5400,
      },
      {
        id: 'stop-amit-2',
        attendance_id: 'att-amit-today',
        user_id: employeeAmitId,
        latitude: 28.5708,
        longitude: 77.3261,
        address_name: 'Client Site: Alpha Infotech, Sector 18',
        start_time: `${todayStr}T11:30:00.000Z`,
        end_time: `${todayStr}T13:45:00.000Z`,
        dwell_duration_seconds: 8100,
      },
    ],
    locationWaypoints: [
      {
        id: 'wpt-1',
        attendance_id: 'att-amit-today',
        user_id: employeeAmitId,
        latitude: 28.6289,
        longitude: 77.3752,
        speed: 0,
        heading: 0,
        accuracy: 8,
        recorded_at: `${todayStr}T09:30:00.000Z`,
      },
      {
        id: 'wpt-2',
        attendance_id: 'att-amit-today',
        user_id: employeeAmitId,
        latitude: 28.6150,
        longitude: 77.3600,
        speed: 35,
        heading: 210,
        accuracy: 6,
        recorded_at: `${todayStr}T11:10:00.000Z`,
      },
      {
        id: 'wpt-3',
        attendance_id: 'att-amit-today',
        user_id: employeeAmitId,
        latitude: 28.5900,
        longitude: 77.3450,
        speed: 28,
        heading: 195,
        accuracy: 7,
        recorded_at: `${todayStr}T11:20:00.000Z`,
      },
      {
        id: 'wpt-4',
        attendance_id: 'att-amit-today',
        user_id: employeeAmitId,
        latitude: 28.5708,
        longitude: 77.3261,
        speed: 0,
        heading: 0,
        accuracy: 5,
        recorded_at: `${todayStr}T11:30:00.000Z`,
      },
    ],
    tamperLogs: [],
    paymentTransactions: [
      {
        id: 'txn-1001',
        company_id: companyId,
        order_id: 'order_cf_98231201',
        cashfree_order_id: 'cf_ord_98231201_live',
        payment_session_id: 'session_cf_98231201',
        employee_name: 'Amit Kumar',
        employee_phone: '+919811122201',
        employee_designation: 'Senior Sales Executive',
        employee_role: 'EMPLOYEE',
        employee_department_id: deptNorthId,
        employee_manager_id: managerPriyaId,
        base_price: EMPLOYEE_BASE_PRICE_INR,
        tax_amount: GST_AMOUNT_INR,
        total_amount: EMPLOYEE_TOTAL_PRICE_INR,
        currency: 'INR',
        status: 'PAID',
        payment_method: 'UPI (GPay / PhonePe)',
        bank_reference: 'CF-UPI-98217342',
        created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
        paid_at: new Date(Date.now() - 14 * 86400000 + 35000).toISOString(),
        invoice_number: 'INV-2026-0001',
      },
      {
        id: 'txn-1002',
        company_id: companyId,
        order_id: 'order_cf_98231202',
        cashfree_order_id: 'cf_ord_98231202_live',
        payment_session_id: 'session_cf_98231202',
        employee_name: 'Sneha Patel',
        employee_phone: '+919811122202',
        employee_designation: 'Client Relationship Officer',
        employee_role: 'EMPLOYEE',
        employee_department_id: deptNorthId,
        employee_manager_id: managerPriyaId,
        base_price: EMPLOYEE_BASE_PRICE_INR,
        tax_amount: GST_AMOUNT_INR,
        total_amount: EMPLOYEE_TOTAL_PRICE_INR,
        currency: 'INR',
        status: 'PAID',
        payment_method: 'NetBanking (HDFC Bank)',
        bank_reference: 'CF-NB-77218399',
        created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
        paid_at: new Date(Date.now() - 7 * 86400000 + 42000).toISOString(),
        invoice_number: 'INV-2026-0002',
      },
      {
        id: 'txn-1003',
        company_id: companyId,
        order_id: 'order_cf_98231203',
        cashfree_order_id: 'cf_ord_98231203_live',
        payment_session_id: 'session_cf_98231203',
        employee_name: 'Vikram Singh',
        employee_phone: '+919811122203',
        employee_designation: 'Logistics Field Agent',
        employee_role: 'EMPLOYEE',
        employee_department_id: deptLogisticsId,
        employee_manager_id: managerPriyaId,
        base_price: EMPLOYEE_BASE_PRICE_INR,
        tax_amount: GST_AMOUNT_INR,
        total_amount: EMPLOYEE_TOTAL_PRICE_INR,
        currency: 'INR',
        status: 'PAID',
        payment_method: 'Corporate Credit Card (Visa)',
        bank_reference: 'CF-CC-49102811',
        created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
        paid_at: new Date(Date.now() - 2 * 86400000 + 28000).toISOString(),
        invoice_number: 'INV-2026-0003',
      },
    ],
  };
}
